### ISSUE TITLE
Build Failure on Mac OSX

### ISSUE THREAD

**Issue by dannypope** [cneben/QuickQanava#10]
Build failures on Mac:

Qt version: Qt5.9
Compiler: clang 64bit and/or gcc

/Users/theUser/Depot/external/QuickQanava/src/qanDraggableCtrl.hpp:251: error: static_cast from 'qan::GroupItem *' to 'QQuickItem *', which are not related by inheritance, is not allowed
                 static_cast<QQuickItem*>(group->getItem()) != static_cast<QQuickItem*>(_targetItem.data()) )  // Do not drop a group in itself

**Comment by cneben** [comment]
Unfortunately, I do not have a working OSX environment to check compilation.

Library has still not been tested on Qt 5.9 (only on an early beta), but it do look more like a forward declaration resolving issue. I can’t test on Clang until the end of the week, but I will try to see if it is related to Qt 5.9, at least on MSVC.

Could you report the sample that actually failed and a “g++/clang --version” please?

**Comment by rakhimov** [comment]
> Unfortunately, I do not have a working OSX environment to check compilation.

Travis supports OS X with homebrew packages.

**Comment by cneben** [comment]
Thanks for the PR, there is c++14 related issues with clang/osx builds (fix in progress).

**Comment by cneben** [comment]
OSX Clang build is now successful (at least on Travis), I am interested by a test in a real environment.

MSVC2015 U3 / Linux g++5.4+ builds are now working from Qt 5.8 to Qt 5.9.1

Clang and lazy template instantiation…
