### ISSUE TITLE
Ambiguity among licensing. 

### ISSUE THREAD

**Issue by knepperd** [cneben/QuickQanava#110]
Some of the source is covered under GPL v3, but the entire project appears to be licensed under BSD, or at least a more permissive license. Can you resolve this ambiguity by updating all of the code to a more permissive license?

**Comment by MikeGitb** [comment]
I don't think it is possible to retroactively change a license unless you get the permission from all the contributors.

**Comment by cneben** [comment]
It is actually BSD licensed, it used to be LGPL some time ago before most external contributions were made. I might have forgotten some old LGPL headers in some files, it will be corrected in next release with a clarification about actual BSD3 license.

**Comment by cneben** [comment]
Fixed in develop.
