### ISSUE TITLE
0.9.0 Discussion - Breaking changes

### ISSUE THREAD

**Issue by cneben** [cneben/QuickQanava#12]
Discussion for edge/node docking support.
Compilation/breaking changes in next release.

**Comment by cneben** [comment]
Follow changes on: https://github.com/cneben/QuickQanava/tree/0.9.0
[X] Change licence to BSD-3 (whole codebase, sub-libraries GTpo/QuickContainers/QuickGeoGL).

**Comment by Jackneill** [comment]
I'd like to help implementing the node in-out ports, if having help faster (i'm completely new to the codebase, never used it, need guidence). You said you are working on the visual dock arch, would you please write it down here?

**Comment by cneben** [comment]
@Jackneill 
After an intensive review of nodeeditor API I’ve started Port/dock implementation, I will push a draft interface this WE in 0.9.0 branch. It’s actually quite complex because I want to have fully customizable IN/OUT ports, and full support for default port delegate and user delegate. Moreover, the interface don’t fit well in qan::Node, it has to be done at the graph (qan::Graph) level which has a quite bloated interface and complex implementation

It’s really not a simple task if you don’t know the lib well, but you can still help a lot by:
- Compiling the actual samples and reporting what is missing from the doc or where you had problems.
- The in/out port support will be implemented in the ‘connector’ sample of 0.9.0 branch.

Implementation of curved edge would probably be a lot easier, you can start reviewing how it is done in the following libs:
- https://github.com/Seneral/Node_Editor_Framework
- https://github.com/aphex-/BrotherhoodOfNode
- https://github.com/paceholder/nodeeditor

Then it’s possible to compile Qt 5.10 and do some testing with PathCubic and the 5.10 QML shape library (https://doc-snapshots.qt.io/qt5-dev/qml-qtquick-pathcubic.html).

The only file you need to modify is actually Edge.qml (the default line with arrow edge delegate). If you want to wait for the first binary snapshot of 5.10, just focus on shape control points generation and use a QML Canvas for testing the display.

Thanks for your contribution proposition
B.

**Comment by cneben** [comment]
First draft: (See commit b524005)

![image](https://user-images.githubusercontent.com/13402251/29242041-f2e4f17a-7f85-11e7-9e2a-bb7842c266dd.png)

User interface:

```
  var n11 = graph.insertNode()
  n11.label = "N11"; n11.item.x = 50; n11.item.y = 50
  var n12 = graph.insertNode()
  n12.label = "N12"; n12.item.x = 50; n12.item.y = 150

  var n2 = graph.insertNode()
  n2.label = "N2"; n2.item.x = 250; n2.item.y = 100

  var p1 = graph.insertInPort(n2);
  p1.label = "IN #1"
  var p2 = graph.insertInPort(n2);
  p2.label = "IN #2"

  var e1 = graph.insertEdge(n11, n2);
  var e2 = graph.insertEdge(n12, n2);
  graph.bindEdgeDestination(e1, p1)
  graph.bindEdgeDestination(e2, p2)

```
Out port support is comming, it still need a lot of cleaning, for the moment, there is no edge/port mapping, implementation is only visual.

**Comment by Jackneill** [comment]
```qml
import QtQuick 2.7
import QtQuick.Controls 2.0
import QtQuick.Layouts 1.3

ApplicationWindow {
    visible: true
    width: 800
    height: 800
    title: qsTr("Hello World")

    property real defaultOffset: 200
    property real xDistance: endRect.x - (startRect.x + 20)
    property real minimum: Math.min(defaultOffset, Math.abs(xDistance))
    property real verticalOffset: xDistance <= 0 ? -minimum : 0
    property real ratio: xDistance <= 0 ? 1 : 0.5

    property real cp1_x: startRect.x + minimum * ratio
    property real cp1_y: startRect.y + verticalOffset
    property real cp2_x: endRect.x - minimum * ratio
    property real cp2_y: endRect.y + verticalOffset

    Rectangle {
        id: startRect
        color: "black"
        height: 20
        width: 20
        x: 100
        y: 200
        z: 1
        onXChanged: canvas.requestPaint()
        onYChanged: canvas.requestPaint()

        MouseArea {
            anchors.fill: parent
            drag.target: parent
            drag.axis: Drag.XandYAxis
        }
    }

    Rectangle {
        id: endRect
        color: "black"
        height: 20
        width: 20
        x: 500
        y: 600
        z: 1
        onXChanged: canvas.requestPaint()
        onYChanged: canvas.requestPaint()

        MouseArea {
            anchors.fill: parent
            drag.target: parent
            drag.axis: Drag.XandYAxis
        }
    }

    Canvas {
        id: canvas
        anchors.fill: parent

        onPaint: {
            var ctx = getContext("2d")
            ctx.fillStyle = Qt.rgba(1, 1, 1, 1)
            ctx.fillRect(0, 0, canvas.width, canvas.height)
            ctx.strokeStyle = Qt.rgba(0, 0, 0, 1)
            ctx.lineWidth = 1
            ctx.beginPath()
            ctx.moveTo(startRect.x + 20, startRect.y)
            ctx.bezierCurveTo(cp1_x, cp1_y, cp2_x, cp2_y, endRect.x, endRect.y)
            ctx.stroke()
            ctx.closePath()
            ctx.beginPath()
            ctx.moveTo(cp1_x, cp1_y)
            ctx.lineTo(cp2_x, cp2_x)
            ctx.stroke()
            ctx.closePath()
            print(startRect.x + 20, startRect.y, cp1_x, cp1_y, cp2_x, cp2_y,
                  endRect.x, endRect.y)
        }
    }
}
```
https://i.imgur.com/zKOG0FL.png

Bezier curve using nodeeditor's code.

i have tried editing Edge.qml:
```qml
Qan.EdgeItem {
    id: edgeItem
    property color color: style ? style.lineColor : Qt.black

    /*Qgl.Arrow {
        anchors.fill: parent
        id: arrow
        visible: edgeItem.visible && !edgeItem.hidden
        p1: edgeItem.p1
        p2: edgeItem.p2
        p2CapSize: edgeItem.style ? edgeItem.style.arrowSize : 4
        lineWidth: edgeItem.style ? edgeItem.style.lineWidth : 2
        color: edgeItem.color
    }*/
    Path {
        id: arrow
        startX: edgeItem.p1.x
        startY: edgeItem.p1.y

        property real defaultOffset: 200
        property real xDistance: edgeItem.p2.x - (edgeItem.p1.x + 20)
        property real minimum: Math.min(defaultOffset, Math.abs(xDistance))
        property real verticalOffset: xDistance <= 0 ? -minimum : 0
        property real ratio: xDistance <= 0 ? 1 : 0.5

        property real cp1_x: edgeItem.p1.x + minimum * ratio
        property real cp1_y: edgeItem.p1.y + verticalOffset
        property real cp2_x: edgeItem.p2.x - minimum * ratio
        property real cp2_y: edgeItem.p2.y + verticalOffset

        PathCubic {
            x: edgeItem.p2.x
            y: edgeItem.p2.y
            relativeControl1X: arrow.cp1_x
            relativeControl1Y: arrow.cp1_y
            relativeControl2X: arrow.cp2_x
            relativeControl2Y: arrow.cp2_y
        }
    }
}
```
But no edge appears with this.

**Comment by Jackneill** [comment]
The problem was that Path is not a visual type, therefore nothing appears. (the docs are a bit clearer now (https://codereview.qt-project.org/#/c/203504/ https://bugreports.qt.io/browse/QTBUG-62799 https://code.qt.io/cgit/qt/qtdeclarative.git/tree/src/quick/util/qquickpath_p.h#n77)).
So using Shape/ShapePath solves it:
`Edge.qml`:
```qml
import QtQuick 2.7
import QtQuick.Layouts 1.3
import QtQuick.Shapes 1.0

import QuickQanava 2.0 as Qan
import QuickGeoGL 1.0 as Qgl
import "qrc:/QuickGeoGL" 1.0 as Qgl

Qan.EdgeItem {
    id: edgeItem

    property color color: style ? style.lineColor : Qt.black

    Shape {
        //anchors.fill: parent
        visible: edgeItem.visible && !edgeItem.hidden
        asynchronous: true

        ShapePath {
            id: arrow
            startX: edgeItem.p1.x
            startY: edgeItem.p1.y
            capStyle: ShapePath.FlatCap //edgeItem.style ? edgeItem.style.arrowSize : 4
            strokeWidth: edgeItem.style ? edgeItem.style.lineWidth : 2
            strokeColor: edgeItem.color
            strokeStyle: ShapePath.SolidLine
            fillColor: "transparent"

            property real defaultOffset: 200
            property real xDistance: edgeItem.p2.x - (edgeItem.p1.x + 20)
            property real minimum: Math.min(defaultOffset, Math.abs(xDistance))
            property real verticalOffset: xDistance <= 0 ? -minimum : 0
            property real ratio: xDistance <= 0 ? 1 : 0.5
            property real cp1_x: edgeItem.p1.x + minimum * ratio
            property real cp1_y: edgeItem.p1.y + verticalOffset
            property real cp2_x: edgeItem.p2.x - minimum * ratio
            property real cp2_y: edgeItem.p2.y + verticalOffset

            PathCubic {
                x: edgeItem.p2.x
                y: edgeItem.p2.y
                /*relativeControl1X: arrow.cp1_x
                relativeControl1Y: arrow.cp1_y
                relativeControl2X: arrow.cp2_x
                relativeControl2Y: arrow.cp2_y*/
                control1X: arrow.cp1_x
                control1Y: arrow.cp1_y
                control2X: arrow.cp2_x
                control2Y: arrow.cp2_y
            }
        }
    }
}
```
https://i.imgur.com/TglsjcZ.png

**Comment by cneben** [comment]
Well done, thank you Márk !

I will push the latest docking/port code ASAP, and try to integrate a new style option in edge style to ease development of curved edge and integrate your code in dev branch.

**Comment by cneben** [comment]
Add multiple docks and dock orientation support for ports.

![image](https://user-images.githubusercontent.com/13402251/29794766-b34ddf4c-8c49-11e7-91de-7d3f48fc68b5.png)

Still not enough time to integrate shape edges...

**Comment by cneben** [comment]
![image](https://user-images.githubusercontent.com/13402251/29941078-87bdf39a-8e91-11e7-97f3-39ad0740d85a.png)

Full in/out port and dock support, with visual connection enabled.

**Comment by cneben** [comment]
Lot of work still necessary on curved edges !
(with Qt 5.10 first binary snapshot)

![image](https://user-images.githubusercontent.com/13402251/30015986-6339fc16-9153-11e7-93f0-ba048e9b48ef.png)

**Comment by Jackneill** [comment]
Looking into it

**Comment by Jackneill** [comment]
That is actually the algorithm working right, since, C is the "left port" in every connection and all the others are the "right ports" (and in node editors' code there are only ports on the left and right side of the node). And the flow graph is indented to flow to the right (if not: https://youtu.be/pxMXjSvlOFw?t=84 have that curve so it goes a bit around the node geom).
But we can achieve the same line shape in all direction with the following changes:
```qml
property real xDistance: eX - sX
property real ratio: Math.abs(xDistance) <= 0 ? 1 : 0.5
property real cp1_x: sX + xDistance * ratio
property real cp1_y: sY
property real cp2_x: eX - xDistance * ratio
property real cp2_y: eY
```
where s(X|Y) is the starting point and e(X|Y) is the ending point.

**Comment by cneben** [comment]
Hello Márk,

The fix is ok, but I think a more robust solution with control points generated from c++ (qan::EdgeItem) is needed:
  - A point must be available at edge center to bind hyper edges (and there is no interpolation method available for now on path item, such as QLineF::pointAt() ).
  - When connecting nodes with “inverted” ports (for example, a link between a source with left port to a destination with right port), more control points are needed to avoid collision with either source or destination.

Unfortunately, there is still no itemAt() or simple “collision detection” available for Qt Quick Shape, so right click on edge or visual hyper edge connection couldn’t be done currently (Shape also inherit Item, so childAt() might work, it has to be tested). 
https://bugreports.qt.io/browse/QTBUG-61857

I will start implementing a visual arrow item using a filled path, then a simple algorithm for c1/c2 generation, and have a test to ensure rendering is successful with two quadratic curves:

![image](https://user-images.githubusercontent.com/13402251/30053342-b681cfae-9228-11e7-9846-e87029ce342d.png)

Then a more complex solution to support “opposed ports” has to be found.

**Comment by cneben** [comment]
77bf35b
(with control points displayed for debugging)

![image](https://user-images.githubusercontent.com/13402251/30161684-e998681c-93d1-11e7-9116-c59e5d6d2a47.png)

Still need to generate Bezier curve tangent angle at curve end to fix arrow orientation:
![image](https://user-images.githubusercontent.com/13402251/30161749-2d70b620-93d2-11e7-8570-aa3d7c554615.png)

**Comment by cneben** [comment]
With excellent cubic spline interpolation/derivation code from http://www.paulwrightapps.com/blog/2014/9/4/finding-the-position-and-angle-of-points-along-a-bezier-curve-on-ios

![image](https://user-images.githubusercontent.com/13402251/30177124-1018e7fe-9405-11e7-8306-cbd8307bcc56.png)
