### ISSUE TITLE
How does one do anti-aliasing on the arrows?

### ISSUE THREAD

**Issue by enjoysmath** [cneben/QuickQanava#131]
Right now, my Hello World arrows are looking pretty aliased, so was wondering how to apply anti-aliasing to them.

**Comment by cneben** [comment]
Unfortunately, I didn't suceed to apply antialiasing only on edges. Without application level supersampling, you probably have to write your own shader to draw antialiased lines.

If you have only a medium sized graph, you can enable supersampling before QCoreApplication initialization in your main.cpp:
```
        QSurfaceFormat format;
        format.setSamples(4);
        QSurfaceFormat::setDefaultFormat(format);
```
