### ISSUE TITLE
Integration with CXXGraph Library

### ISSUE THREAD

**Issue by ZigRazor** [cneben/QuickQanava#151]
Hi, very good work.
I would ask you if is possible to collaborate to integrate the CXXGraph Library and it's data-structure in QuickQanava.
Could be a good oppurtunities for both, to integrate a visualization tool for the CXXGraph library and to Intregrate a well-done data structure representation of graph in C++ language.

You can find the CXXGraph project at [this link](https://github.com/ZigRazor/CXXGraph).

It is just a proposal, but I think can be useful for both the project development.
Thank you so much

**Comment by emmenlau** [comment]
I think CXXGraph looks promising but I'm under the impression that its license is more restrictive than the one of QuickQanava, which seems to be BSD-licensed. IMHO if the two projects would integrate in an inseparable way, the more restrictive license would apply?

**Comment by ZigRazor** [comment]
yes, but if needed as owner of the project, I can change License to get the best and open License as possible.

**Comment by ZigRazor** [comment]
In any case, for AGPL-3.0 just cite the code license and copyright in a notice and you can do anything with the code.

**Comment by ZigRazor** [comment]
> This sounds of course fine!

If needed and we start the integration I'm available to change the licence.

**Comment by emmenlau** [comment]
> > This sounds of course fine!
> 
> If needed and we start the integration I'm available to change the licence.

I'm not the one to take that decision, but IMHO before QuickQanava can integrate anything from CXXGraph, either one of the two projects would need to change its license (unless the integration is done in such a separable way that CXXGraph remains fully optional, but even then the license would depend on whether CXXGraph is enabled).

@ZigRazor , I see that you are a core developer from CXXGraph. But I'd like to mention that _if_ other people contributed source code to CXXGraph, its at least possible that you need to consult them before changing the license. I'm no expert in this field, and different countries may have different regulations, but I'm just trying to raise that point to everyones awareness. While I personally would find it great if CXXGraph where BSD-licensed (or using some other compatible license), there may be work ahead before this can actually happen. In the worst case it should suffice to re-write all the code that other contributors added, but again, I'm not a lawyer.

**Comment by emmenlau** [comment]
See for example https://opensource.guide/legal/#:~:text=If%20you're%20the%20sole,in%20order%20to%20change%20licenses.

**Comment by ZigRazor** [comment]
I'm the code owner and the mantainer, I choose this license and I can change it, also with the approval of the collaborators

**Comment by emmenlau** [comment]
> I'm the code owner and the mantainer, I choose this license and I can change it, also with the approval of the collaborators

Yes, with the approval of the collaborators its no problem.

**Comment by emmenlau** [comment]
CXXGraph looks cool, would be nice if both projects can benefit!
