### ISSUE TITLE
problem in Qan.EdgeStyle.Curved

### ISSUE THREAD

**Issue by matinjalalitekiyeh** [cneben/QuickQanava#166]
hi there im using qt6.
i think there is a problem on Qan.edgeStyle.Curved. but for other linetypes is ok.

**Comment by matinjalalitekiyeh** [comment]
ASSERT: "divisor < 0 || divisor > 0" in file C:/Qt/6.3.1/mingw_64/include/QtCore/qpoint.h, line 299

**Comment by cneben** [comment]
@matinjalalitekiyeh Sorry, not enought infos to investigate this one: what is you OS, do you have a screenshot or sample reference ?

**Comment by cneben** [comment]
Fixed in #173
