### ISSUE TITLE
Build fails with Qt 6.4 and MSVC

### ISSUE THREAD

**Issue by petrmanek** [cneben/QuickQanava#175]
Hello!

I have recently switched over to Windows to see if my app still builds there, and encountered the following compilation error with QuickQanava 2.1.0 (9af64e6dc5a85796bedfdf666a9244dc2fd69da1), Qt 6.4.0, Windows SDK 10.0.18362.0 and msvc2019_64, v142). The compiler message reminds me of those seen in #159 and #118.

```
3>C:\myproject\lib\quickqanava\src\../QuickContainers/include/qcmContainer.h(436,4): error C2039: 'indexOf': is not a member of 'qcm::adapter<C,T>'
3>        with
3>        [
3>            C=QVector,
3>            T=qan::Node *
3>        ] (compiling source file C:\myproject\lib\quickqanava\src\qanBehaviour.cpp)
3>C:\myproject\lib\quickqanava\src\../QuickContainers/include/qcmContainer.h(436): message : see declaration of 'qcm::adapter<C,T>'
3>        with
3>        [
3>            C=QVector,
3>            T=qan::Node *
3>        ] (compiling source file C:\myproject\lib\quickqanava\src\qanBehaviour.cpp)
3>C:\myproject\lib\quickqanava\src\../QuickContainers/include/qcmContainer.h(436): message : while compiling class template member function 'int qcm::Container<QVector,node_t *>::indexOf(T) noexcept const'
3>        with
3>        [
3>            node_t=qan::Node,
3>            T=qan::Node *
3>        ] (compiling source file C:\myproject\lib\quickqanava\src\qanBehaviour.cpp)
```

Similar messages can be observed for `T=qan::Group *` and `T=qan::EdgeItem *`. There is also the following message:

```
3>C:\myproject\lib\quickqanava\src\../QuickContainers/include/qcmContainer.h(430,4): error C2039: 'contains': is not a member of 'qcm::adapter<C,T>'
3>        with
3>        [
3>            C=QVector,
3>            T=QObject *
3>        ] (compiling source file C:\myproject\lib\quickqanava\src\qanStyleManager.cpp)
3>C:\myproject\lib\quickqanava\src\../QuickContainers/include/qcmContainer.h(430): message : see declaration of 'qcm::adapter<C,T>'
3>        with
3>        [
3>            C=QVector,
3>            T=QObject *
3>        ] (compiling source file C:\myproject\lib\quickqanava\src\qanStyleManager.cpp)
3>C:\myproject\lib\quickqanava\src\../QuickContainers/include/qcmContainer.h(430): message : while compiling class template member function 'bool qcm::Container<QVector,QObject *>::contains(const T) noexcept const'
3>        with
3>        [
3>            T=QObject *
3>        ] (compiling source file C:\myproject\lib\quickqanava\src\qanStyleManager.cpp)
3>C:\myproject\lib\quickqanava\src\qanStyleManager.cpp(68): message : see reference to function template instantiation 'bool qcm::Container<QVector,QObject *>::contains(const T) noexcept const' being compiled
3>        with
3>        [
3>            T=QObject *
3>        ]
```

I would be happy to test any fixes/patches that you propose. As always, many thanks for your help in advance!

**Comment by petrmanek** [comment]
@cneben Can I help with any more tests/logs?

**Comment by cneben** [comment]
It's strange, I've just build it successfully with Qt 6.4.1 and g++. I will add CI for MSVC and Qt6.4.1 this afternoon to have a test.

By the way a lot of new CMake configuration tools have been added in 6.2.0 (`qt_add_qml_module()`), I think it is necessary to rewrite CMake configuration and support only Qt > 6.2.0. Is it a problem for you, I don't think anyone need Qt [6.0.0, 6.2.0[ support ?

**Comment by petrmanek** [comment]
> It's strange, I've just build it successfully with Qt 6.4.1 and g++. I will add CI for MSVC and Qt6.4.1 this afternoon to have a test.

Very well. In the meantime I have updated to Qt 6.4.1 as well. I can confirm that both macOS and Linux builds work without issues there.


> By the way a lot of new CMake configuration tools have been added in 6.2.0 (`qt_add_qml_module()`), I think it is necessary to rewrite CMake configuration and support only Qt > 6.2.0. Is it a problem for you, I don't think anyone need Qt [6.0.0, 6.2.0[ support ?

This is not a problem for me, I am running Qt 6.4.1, and hoping to pin my builds to the upcoming 6.5 LTS in the foreseeable future.

**Comment by cneben** [comment]
@petrmanek I think it is fixed on both master and develop, could you close after checking the patch please ?

**Comment by petrmanek** [comment]
@cneben Great news, will try it tomorrow! Thank you!

**Comment by petrmanek** [comment]
@cneben Results are in, and I can happily confirm that the latest revision in master (9af0dbb3a44007b35dcdee9a009f5a6f91834d13) builds with my MSVC toolchain. Thank you again for a your help, and have a good day! :rocket:
