### ISSUE TITLE
Opacity issue in Qan.GraphView

### ISSUE THREAD

**Issue by topper7** [cneben/QuickQanava#176]
Hi,

Have you encountered the following issue while working with QuickQanava?
I'm using Qt 5.11(+QML) and QuickQanava from 20201205  (probably version 0.10.0)

I have a QML module which is a plugin in main app and it uses Qan.GraphView
When I call a Popup control with _background: Rectangle{}_ property
the background like transparent and some of the controls behind it are visible.
If I add opacity property like this
 _
Popup {
  ....
     background: Rectangle {
    ...
    opacity: 0.999
    ...
    }
}_
the background is opaque as expected and it overlaps all controls behind it.

The same Popup control doesn't have any background transparency issues when Qan.GraphView is not applied.

Why the background like transparent by default when using Qan.GraphView? What do I need to fix in QuickQanava to prevent the Popup control background from becoming transparent?

**Comment by cneben** [comment]
Hi, you should really update to a recent develop version if you could.

Qt5 `Popup` is sometime difficult to use (event, freeze problems on Windows when it popup outside main window): probably you should reparent all your popups to `Overlay.overlay`, and then map desired position from Qan.GraphView to glbal view:

```
Popup {
    id: myPopup
    parent: Overlay.overlay
}
```
Then, from your node delegate:
```
  let global = mapToItem(Overlay.overlay, 0, 0)
  myPopup.x = Math.min(Overlay.overlay.width - myPopup.width - 10, global.x + 10)
  myPopup.y = Math.min(Overlay.overlay.height - myPopup.height - 10, global.y + 10)
  myPopup.open()
```

**Comment by topper7** [comment]
It doesn`t seem to work (

I've already had the popups reparented in the plugin:
```

Popup {
...
        parent: Overlay.overlay
                x: Math.round((parent.width - width) / 2)
                y: Math.round((parent.height - height) / 2)
...
        background: Rectangle {
...
        }
...   
}
```

And the background is transparent anyway until I add "opacity: 0.999" into "background: Rectangle { ...".
Only then the background becomes solid.

Moreover I don't have access to rewriting anything in the main app where popups should be reparented as I'm responsible only for plugin part.

PS using Ubuntu 21.10
