### ISSUE TITLE
Unique selection (and forbid multiple selection)

### ISSUE THREAD

**Issue by arabine** [cneben/QuickQanava#183]
Is it possible to select only one node and forbid the multiple selection? If not, I can develop a patch maybe?

**Comment by cneben** [comment]
Hi @arabine, unfortunately, it is not possible for the moment since `qan::Graph::SelectionPolicy` only allow CTRL or no selection policies.
I am currently adding a `qan::Graph::enableMultipleSelection` settings to implement the desired behaviour, please follow the #183 mention on develop.

**Comment by cneben** [comment]
- [ ] Add `multipleSelectionEnabled` support to `qan::Graph`.
- [ ] Modify the `selection` sample to demonstrate `multipleSelectionEnabled`.
- [ ] Enforce policy for "window selection" (CTRL + drag).
- [ ] Add documentation.

**Comment by arabine** [comment]
Ok saw it, wonderful. Maybe the selection rect should be disabled when the single selection is selected? (this is my case, we do not want selection rect).

**Comment by cneben** [comment]
For future reference, `selectionRectEnabled` has been enabled on `qan::Navigable` the handle that case.
