### ISSUE TITLE
Modify the cmake build to make use of Qt6 modern cmake features

### ISSUE THREAD

**Issue by emmenlau** [cneben/QuickQanava#207]
The [QuickQanava](https://github.com/cneben/QuickQanava) build seems to be implemented before Qt offered the very helpful cmake tooling for QML modules. Much of what the build does manually can now be achieved much nicer with cmake tooling. There would be multiple benefits:
 - QuickQanava would provide automatically generated `qmltypes` files, which allow the Linter `qmllint` to work correctly
 - The manual maintenance of `qmldir` files is no longer needed
 - Installation with cmake works cleanly, which was requested already in https://github.com/cneben/QuickQanava/issues/165
 - The whole build system would be simpler and more consistent with Qt guidelines

For that, the build should follow https://doc.qt.io/qt-6/qt-query-qml-module.html#example

I can implement this and make a PR if people are interested?

**Comment by emmenlau** [comment]
I have created an implementation of this and can provide is soon as a PR. But I think this would also "modernize" quite a bit some other details of QuickQanava, and I wonder if that is acceptable?

Things that could/should be changed:
 - No longer a need for manually maintained `qmldir` files, they can be auto-generated
 - No longer a need to explicitly import the qrc-file in QML
 - No longer a need to explicitly register C++ QML types in the plugin
 - Maybe the whole manually created plugin is unnecessary? Modern Qt seems to do all that automatically?

**Comment by cneben** [comment]
Hi @emmenlau, thank for you detailled BR: using newest Qt6 features is a very good idea and a good move to clean the build system.
Unfortunately, I am still stuck to Qt5.15 for at least few months on a closed-source project and I've no time to maintain two parallel branches... (moreover, Qt 6.5 will probably be the first stable version of Qt6 ;) )

If you are willing to maintain a Qt6 branch, I would be very happy to support your work and it would give our users (I know at least 4 commercial projects using QuickQanava) more time to prepare for change.

I am OK with all of your points (except perhaps no using qrc, I've bad memories about that, perhaps specific to Qt5). I would even add:
- Switch to c++17 pehaps even c++20.
- Remove every use of QVector and switch to std containers where possible (_selectedNodes, etc.), really the Qt move of switching QList / QVector make me want to stop using Qt option when there is an std alternative.

**Comment by emmenlau** [comment]
Dear @cneben , thanks a lot for the thumbs up, sounds a good way forward! In the next two weeks we are completely booked with other projects, but afterwards I'm happy to share my progress and maintain it in a Qt 6 branch!

**Comment by emmenlau** [comment]
I think recent master has some of these issues addressed, is that correct? Is this issue here fully covered, or what remains to nicely support modern Qt 6 cmake?

**Comment by cneben** [comment]
Well, most of it, but I still maintain qmldir and qrc files + no use of QML_ELEMENT macro.
I think we should close that one that has too much history on old branches, but there is still a lot of work to do (I'am not sure it's 100% compatible with my actual proprietary code using .qrc so I won't put much energy on this until next major release (>=2.5).

**Comment by cneben** [comment]
Closing for #248
