### ISSUE TITLE
EdgeStyle for custom Edge subclass is ignored

### ISSUE THREAD

**Issue by petrmanek** [cneben/QuickQanava#211]
By necessity I found that when a `qan::EdgeStyle*` is provided for a custom edge type, as described in the documentation, the graph ignores it and replaces it with the default style. This seems to be due to a missing line `qanGraph.cpp` that appears to be an oversight.

Consider the [following line](https://github.com/cneben/QuickQanava/blob/develop/src/qanGraph.cpp#L409):

```cpp
nodeItem->setStyle(qobject_cast<qan::NodeStyle*>(&style));
```

In this context, it appears for 2 out of 3 possible cases: nodes, groups, but not edges. From that, I conclude that its omission is unintentional. This is also supported by the observation that adding the missing equivalent of this line appears to provide a fix. Here is a patch that implements this:

```patch
diff --git a/src/qanGraph.cpp b/src/qanGraph.cpp
index 604ac3f..ef64c92 100644
--- a/src/qanGraph.cpp
+++ b/src/qanGraph.cpp
@@ -415,6 +415,7 @@ QQuickItem* Graph::createFromComponent(QQmlComponent* component,
                 edge->setItem(edgeItem);
                 edgeItem->setEdge(edge);
                 edgeItem->setGraph(this);
+                edgeItem->setStyle(qobject_cast<qan::EdgeStyle*>(&style));
                 _styleManager.setStyleComponent(edgeItem->getStyle(), component);
             }
         } else if (group != nullptr) {
```

Until this is mainlined, I will be mitigating this behavior by explicitly calling `EdgeItem::setStyle` after inserting each edge.

**Comment by petrmanek** [comment]
Ping @cneben

**Comment by petrmanek** [comment]
@cneben Could we please get this integrated before 2.4.0? It is literally a single-line fix.

**Comment by cneben** [comment]
Hi @petrmanek yes there is still a lot of polishing before 2.4.0 (not until this WE). I will definitively merge that one which is also causing a refresh problem in one of my app. Thank-you !

**Comment by petrmanek** [comment]
Excellent, thank you for getting around to this! :+1:
