### ISSUE TITLE
:construction: Why not use a Flickable as a Navigable (in order to have a bounding box behavior for the canvas)

### ISSUE THREAD

**Issue by emmenlau** [cneben/QuickQanava#232]
There is something that I'm missing in QuickQanava: The `Navigable` canvas allows to zoom and pan in such a way that none of the graph nodes remain visible (empty space). For me, that is not such a good behavior. I would prefer if zooming and panning is only allowed in such a way that there is not too much empty space visible.

More concretely, that means:
 - If the graph has a bounding box `B`, then lets call `Bp` the bounding box plus some offset (like 10% extra padding)
 - Do not allow to zoom out more than to make `Bp` fully visible
 - Do not allow to pan outside of `Bp`

I think that is the default behavior of a [Flickable](https://doc.qt.io/qt-6/qml-qtquick-flickable.html), if I'm not mistaken? Could the `Navigable` be replaced with `Flickable` to get a similar behavior, but with some of the extra nice zooming and panning behavior of Qt default?

**Comment by cneben** [comment]
Hi @emmenlau I actually tried to implement a "zoom on mouse" with Fickable with early Qt5 version and never succeed to get it working, hence the custom qan::Navigable implementation.

It would be especially nice for touch support and scrollbar support. Won't have time in the next week to have a try, but can review a PR ! This feature would be extremely nice and is a P1 on my side...
