### ISSUE TITLE
QMenu on node right-clicked moves the node after the menu has closed

### ISSUE THREAD

**Issue by Jackneill** [cneben/QuickQanava#29]
Project to reproduce the bug: 
[qqrctest.zip](https://github.com/cneben/QuickQanava/files/1673899/qqrctest.zip)

- Press right clicked on the node
- Menu appears, click to make the menu disappear
- Move the mouse, notice that the node moves
- Excepted behavior: Node has no "mouse pressed status"

**Comment by cneben** [comment]
Fixed in branch 'develop'.
