### ISSUE TITLE
Crash when dragging over a node if the source is not a QQuickItem

### ISSUE THREAD

**Issue by fkorsa** [cneben/QuickQanava#30]
This can happen for example when dragging files from the explorer into the application window, over a node.

These two lines are the issue:
QQuickItem* sourceItem = qobject_cast<QQuickItem*>(event->source());
            QVariant draggedStyle = sourceItem->property( "draggedStyle" ); // The source item (usually a style node or edge delegate must expose a draggedStyle property.

The variable sourceItem should be checked for nullity before being accessed.

**Comment by fkorsa** [comment]
Inside this method: 

DraggableCtrl<Node_t, NodeItem_t>::handleDragEnterEvent

**Comment by cneben** [comment]
Fixed in branch 'develop' thanks for the report.
