### ISSUE TITLE
Cannot click on connector (its real place is shifted from where its visually drawn)

### ISSUE THREAD

**Issue by Jackneill** [cneben/QuickQanava#32]
The example project from https://github.com/cneben/QuickQanava/issues/29 can demostrate this.
Try to move the node's connector: you can't, it just moves the node. But if you click a bit shifted away, to the top-left, compared to the connector, then you can grab it. In my personal project on windows i cant even click on a node but have to shift. Right click also does not appear where it should but shifted to the right-bottom direction. Seems universal. And yes, this is a windows-only issue....:)

**Comment by Jackneill** [comment]
I should probably add that on linux everything works.
Kit on win: Qt 5.10.1 MSVC2015 64bit

**Comment by cneben** [comment]
Unfortunately, I can't reproduce that bug with qqrctest.zip: connector is fully draggable on its whole surface on my system (Win 10, same kit). 

Could you paste a GIF video of the problem ? (http://www.screentogif.com/)

**Comment by Jackneill** [comment]
![node](https://user-images.githubusercontent.com/451076/35805107-dc762078-0a7a-11e8-98f4-987007e83c4b.gif)

**Comment by Jackneill** [comment]
![test](https://user-images.githubusercontent.com/451076/35805449-3a0779fc-0a7c-11e8-9594-552323d46b8f.gif)
