### ISSUE TITLE
Feature request: connectorDelegate in qanGraph

### ISSUE THREAD

**Issue by 0dnb0** [cneben/QuickQanava#43]
Hi,

is it possible to extend qanGraph with a connectorDelegate for a simple override of the connector?

Best regards,

Marco

**Comment by cneben** [comment]
I will think about it for a later release, but you already have: connectorItem property in Qan.Graph to customize default connector behaviour.

This feature is demonstrated in connector sample l. 84 in https://github.com/cneben/QuickQanava/blob/master/samples/connector/custom.qml
