### ISSUE TITLE
Using C++ class enums in QML

### ISSUE THREAD

**Issue by Letrab** [cneben/QuickQanava#44]
Due to a bug in Qt (already there since 5.8) the registrations of C++ enum classes in QML are not handled properly (because of this bug: https://bugreports.qt.io/browse/QTBUG-58454).

E.g. an example is that in QML Qan.PortItem.Out is not known.
Which causes that the function insertPort cannot be called with custom parameters.

Fix is easy by manually declaring the enum with Q_DECLARE_METATYPE , as normally Q_ENUM should do already... Or remove the "class" in "enum class".

_Affected enums:_
**NodeItem:**
    Q_ENUM(Connectable)
    Q_ENUM(Dock)
**PortItem:**
    Q_ENUM(Type)
    Q_ENUM(Multiplicity)
**Style:**
    Q_ENUM(FillType)
    Q_ENUM(EffectType)
    Q_ENUM(LineType)

**Comment by cneben** [comment]
Thanks for the PR, I will merge in develop with latest changes for 0.10.0.
