### ISSUE TITLE
Folded Groups issues: Edges shown when dragging + drop nodes when hidden

### ISSUE THREAD

**Issue by Letrab** [cneben/QuickQanava#48]
I am using the latest master revision and the Groups sample project:

There are happening a few strange things, in my understanding:

- Add a Node to a Group and make a connection with a Node outside this group.
Now fold(close) the group. As expected the Node and connecting edge is also hidden. 
Now move the visible Node around. Now the hidden edge becomes visible suddenly... This seems unwanted behaviour to me?

- When folding a Group, it is still possible to drop a Node into the invisible Group. This is very confusing, as when re-ordering/dragging nodes around, suddenly they can become part of a hidden Group.
Which also means that a very big group (in size) almost always will catch a drag/drop action of a Node...

Thank you very much for your work! Thumbs up!

**Comment by cneben** [comment]
Thanks for your comment (please do not forget to star :)

Looking into that issue asap, it look like a regression.

**Comment by Letrab** [comment]
Note: it was already the case in previous version (c3aa82307b35e22a43e9befd26aac6705f942a1d).
Note2: I am building on MacOS with clang with Qt 5.10.1

**Comment by cneben** [comment]
Fixed (don't know how I could have missed that one, thanks for the report).

**Comment by Letrab** [comment]
Sorry for digging this up and thanks for all the fixed. 

Would it be possible to contact you directly for a few questions, not issue related?
Unfortunately your listed email address isn't functional: For any questions, please contact: benoit@destrat.io

Please contact me at bartel.eerdekens a.t. luminex.be

Thanks in advance.
