### ISSUE TITLE
(Un)Selection misbehaviour

### ISSUE THREAD

**Issue by Letrab** [cneben/QuickQanava#51]
When using the Groups sample project with the latest master revision, strange behaviour is obtained when unselecting a Node (haven't tried with Groups yet) via CTRL + click.

Steps to reproduce + problem:

* Select N3
* Press CTRL
* Select N2
* Release CTRL
* Move N2
 	N2 and N3 move
* Press CTRL
* Select N3
* Click empty space (unselect all)
 	NOK: N2 gets unselected, N3 is not [unselect bug]
* Drag N3 (no first click, directly drag)
 	OK
* Drag N2
 	OK
* Keep N2 selected and drag N3
 	NOK: Both N2 and N3 move
* Keep N2 selected and drag N2
 	OK: Only N2 moves [+unselect bug]

After this sequence I cannot find a way to unselect N3 (visually at least)...

Sorry for the spam, I just like to contribute to make your library even better ;-).

**Comment by cneben** [comment]
Thanks for the report, I really need some automated UI testing !

Fixed on master...
