### ISSUE TITLE
Check OGL context at startup, report error - (Getting application output about ShaderEffectSource)

### ISSUE THREAD

**Issue by yizhoumo** [cneben/QuickQanava#62]
I got tons of the same message when the view is being updated. Is it normal? What should I do about it?

Message:
> ShaderEffectSource: 'recursive' must be set to true when rendering recursively.

BTW, I'm using Qt 5.11.1 with MinGW 5.3 and MSVC2017.

**Comment by yizhoumo** [comment]
I found out that I got no node effect like shadow, along with these messages in Application Output.

> [opengl\qopenglframebufferobject.cpp line 543] OpenGL Error: 1282
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete, missing attachment.

So, it seems to be a OpenGL problem. I checked my environment and I found `QT_OPENGL=angle`. Changing it to `QT_OPENGL=desktop` just works fine, except that the Qt Quick Controlls look wiered, which is not an issue of this repo.

**Comment by cneben** [comment]
Thanks for the report and for fixing the problem ! QuickQanava cannot work without OpenGL HW acceleration (and angle has no HW support). QuickQanava should check for a valid OGL context at startup and output a clean error message when no HW support is found. Title edited, and bug left open with "help needed" tag.

**Comment by Letrab** [comment]
In addition to this, on Mac OS builds, the warning/error will always be shown:

```
QOpenGLFramebufferObject: Unsupported framebuffer format.
QOpenGLFramebufferObject: Framebuffer incomplete, missing attachment.
```

I found the root cause of this error:
https://github.com/Swordfish90/cool-retro-term/issues/12#issuecomment-50771617

Which is confirmed by Qt: http://doc.qt.io/qt-5/qml-qtquick-shadereffectsource.html#format-prop
```
Note: Some OpenGL implementations do not support the GL_ALPHA format.
```

Is it possible to use another format for this? This will solve the issues for mac os.

**Comment by cneben** [comment]
Sorry for missing out your last report: you are right, it has nothing to do with OGL context, but with incorrect use of QML ShaderEffectSource (Appears only on Windows with Qt5.11, 5.10 is OK, Linux was OK too).

Problem should now be fixed, if you could have a test on MacOS...

**Comment by cneben** [comment]
Thanks, it is very tricky to combine shadow effect with transparent background: I think it is now in stable state, I will have more tests on Windows. (BTW, I will have a look to your latest BR on edges this week).
