### ISSUE TITLE
Arrow angle calculation off in special case (curved + short line + equal height)

### ISSUE THREAD

**Issue by Letrab** [cneben/QuickQanava#63]
Hi Benoit,

I found out, by coincidence, that the angle calculation of a curved line could be off, in a special case:

To (easily) reproduce, draw these nodes + edge, with a small distance between the nodes:

```
                var tl = graph.insertNode()
                tl.label = "TL"; tl.item.x = 50; tl.item.y = 50

                var tml = graph.insertNode()
                tml.label = "TML"; tml.item.x = 200; tml.item.y = 50
                graph.insertEdge(tl, tml);
```

This happens at firstly showing:

![screen shot 2018-09-11 at 14 49 47](https://user-images.githubusercontent.com/13414994/45361393-59412000-b5d2-11e8-833e-6e251282a822.png)

I did some tracing already, and it has to do with a special case when the ```cubicCurveAngleAt``` and ```lineAngle``` calculation lie roughly 360 degrees apart... 
I added some tracing as well:

> **POINT 75.0007 74.9993**
> (p1.y() and p2.y())
> **SMALLER -0.0014643**
> (lineAngle, line.dy() is smaller than 0.0)
> **Special case 0.000647655 359.998**
> (result of resp. cubicCurveAngleAt(0.99, cache.p1, cache.p2, cache.c1, cache.c2) and lineAngle(line))
> **qml: Rotation 215.9990081604425**
> (end calculation of 0.4 * ... + 0.6 * ....)

I only was able to draw it correctly by only taking into account the angle of lineAngle(). Probably there is a more pragmatic way solving this.

With a slight drag action of a node, it is already solved, probably some pixel-alignment?
Also afterwards it is very hard to reproduce by just dragging...

Thanks

**Comment by cneben** [comment]
Thanks for the report, the cubic curve interpolation (and tangent angle) code is not very stable for small curves (+/- modulo 2PI!). I've been looking for a well maintained header only geometry library for a long time to avoid maintaining such a code in QuickQanava, eventually I will have a test with @oysteinmyrmo "bezier" lib https://github.com/oysteinmyrmo/bezier.
