### ISSUE TITLE
Edge hidding for overlapping nodes

### ISSUE THREAD

**Issue by cneben** [cneben/QuickQanava#7]
Fix edge auto-hidding when nodes bounding rect are overlapping:

![image](https://cloud.githubusercontent.com/assets/13402251/26349546/61a73bf6-3fb0-11e7-9682-ddb5eed424be.png)

**Comment by emil-sawicki9** [comment]
Z value needs to be changed to be equal to first node.

**Comment by cneben** [comment]
It would fix the problem, except for transparent nodes (edge has Test2 z since a dragged node and its adjacent edges have to be over all other scene content). I think a full (costly) bounding rect overlap test is needed here unfortunately.

**Comment by emil-sawicki9** [comment]
Then maybe SecondNode.z -1 would work?
