### ISSUE TITLE
Runtime error on Ubuntu 18.04 : "QtQuick.Shapes" is not installed

### ISSUE THREAD

**Issue by f4gkr** [cneben/QuickQanava#71]
Cloned the source with Git and compiled with QTCreator, compilation ends without any error.
Running any of the examples fails with the following message:

_QML debugging is enabled. Only use this in a safe environment.
QuickQanava::initialize(): Warning: QuickQanava depends on Qt Quick Shapes library available since Qt 5.10.
QQmlApplicationEngine failed to load component
qrc:/style.qml:43 Type Qan.GraphView unavailable
qrc:/QuickQanava/GraphView.qml:36 module "QtQuick.Shapes" is not installed_

The following packages are installed:
dpkg -l |grep qtquick
ii  qml-module-qtquick-controls:amd64          5.9.5-0ubuntu1                              amd64        Qt 5 Quick Controls QML module
ii  qml-module-qtquick-controls2:amd64         5.9.5-0ubuntu2                              amd64        Qt 5 Qt Quick Controls 2 QML module
ii  qml-module-qtquick-dialogs:amd64           5.9.5-0ubuntu1                              amd64        Qt 5 Dialogs QML module
ii  qml-module-qtquick-extras:amd64            5.9.5-0ubuntu1                              amd64        Qt 5 Quick Extras QML module
ii  qml-module-qtquick-layouts:amd64           5.9.5-0ubuntu1.1                            amd64        Qt 5 Quick Layouts QML module
ii  qml-module-qtquick-privatewidgets:amd64    5.9.5-0ubuntu1                              amd64        Qt 5 Private Widgets QML module
ii  qml-module-qtquick-scene2d:amd64           5.9.5+dfsg-0ubuntu2                         amd64        Qt 5 Quick Scene 2D QML module
ii  qml-module-qtquick-scene3d:amd64           5.9.5+dfsg-0ubuntu2                         amd64        Qt 5 Quick Scene 3D QML module
ii  qml-module-qtquick-templates2:amd64        5.9.5-0ubuntu2                              amd64        Qt 5 Qt Quick Templates 2 QML module
ii  qml-module-qtquick-window2:amd64           5.9.5-0ubuntu1.1                            amd64        Qt 5 window 2 QML module
ii  qml-module-qtquick2:amd64                  5.9.5-0ubuntu1.1                            amd64        Qt 5 Qt Quick 2 QML module
ii  qtquickcontrols2-5-dev:amd64               5.9.5-0ubuntu2                              amd64        Qt 5 Quick Controls 2 development files
ii  qtquickcontrols2-5-doc                     5.9.5-0ubuntu2                              all          Qt 5 Quick Controls 2 documentation
ii  qtquickcontrols5-doc                       5.9.5-0ubuntu1                              all          Qt 5 Quick Controls documentation

**Comment by ruisebastiao** [comment]
"QuickQanava::initialize(): Warning: QuickQanava depends on Qt Quick Shapes library available since **Qt 5.10.**"

You need Qt 5.10 or above

**Comment by f4gkr** [comment]
Ouch... Qt 5.9 is not > 5.10 .... my mistake ?
Qt on this machine is the latest stable package provided by Ubuntu
thanks for your reply and sorry for the report
