### ISSUE TITLE
module “QtQuick.Shapes” is not installed （qt 5.12.2）

### ISSUE THREAD

**Issue by Caprey** [cneben/QuickQanava#79]
Cloned the source with Git and compiled with QTCreator, compilation ends without any error.
Running any of the examples successed with QtCreator,but when i run the release version with the .exe , then the message show up that "module “QtQuick.Shapes” is not installed "

**Comment by Letrab** [comment]
You mean, running the exe yourself, which is being built? So not started via QtCreator?

This is normal, you should package/deploy your .exe with all needed libraries/files.

See: https://doc.qt.io/qt-5/windows-deployment.html and https://wiki.qt.io/Deploy_an_Application_on_Windows

I do recommend the usage of windeployqt, as it does all library dependency resolving for you. Do mind the "qmldir" option, for which you have to specify the path to the folder containing all qml files.

**Comment by Caprey** [comment]
i use "windeployqt test-connector.exe -qmldir D:\Qt\5.12.2\msvc2017_64\qml" to package,and running the exe,but is show up  "module “QtQuick.Shapes” is not installed"

**Comment by Letrab** [comment]
Had to be more specific: The "qmldir" location is the location of your own (project) QML files. So in this case, the location of your QuickQanava checkout (sub-folders are being processed).

**Comment by Caprey** [comment]
yes , my qt install path is "D:\Qt\5.12.2"

**Comment by Letrab** [comment]
Like said, qmldir should not point to your qt installation path, but to your actual QML files of your project. In this case something like

"windeployqt test-connector.exe -qmldir D:\whereveryourcodeis\QuickQanava"

**Comment by Caprey** [comment]
thanks ,that is ok
