### ISSUE TITLE
in example topolopy, when i execute "clear Graph" that is error

### ISSUE THREAD

**Issue by Caprey** [cneben/QuickQanava#81]
in example topolopy, when i execute "clear Graph", the message show "TypeError: Property 'clear' of object qan::FaceGraph_QML_70(0x7884400, "graph") is not a function",so i modify "void                        clear() noexcept;" to " Q_INVOKABLE void  clear() noexcept;" in the file "qanGraph.h" 103 line ,but that still error.

**Comment by cneben** [comment]
Partially fixed by a call to clearGraph(). It actually still crash, probably related to a shared_ptr issue. I will investigate and fix this for next realease.
