### ISSUE TITLE
remove empty group and click will crash

### ISSUE THREAD

**Issue by xiaozia** [cneben/QuickQanava#83]
![image](https://user-images.githubusercontent.com/4347241/56709596-b7330a00-6754-11e9-95f8-df9512ca68fc.png)
remove empty group，and then click in the empty section will crash
![QQ截图20190425123033](https://user-images.githubusercontent.com/4347241/56709869-278e5b00-6756-11e9-8fe5-79f632dafe81.jpg)
![QQ截图20190425123102](https://user-images.githubusercontent.com/4347241/56709873-2c530f00-6756-11e9-8b21-48e145d0ff43.jpg)
`void    Graph::removeGroup( qan::Group* group )
{
    if ( group == nullptr )
        return;

    // Reparent all group childrens (ie node) to graph before destructing the group
    // otherwise all child iems get destructed too
    for ( auto& node : group->get_nodes() ) {
        const auto qanNode = qobject_cast<qan::Node*>(node.lock().get());
        if (qanNode != nullptr)
            group->getItem()->ungroupNodeItem(qanNode->getItem());
    }
    // FIXME: don't like that dynamic cast, probably not necessary

    gtpo_graph_t::remove_group( weak_group_t{std::dynamic_pointer_cast<Group>(group->shared_from_this())} );
}`
removeGroup function has problem, it doesn't remove selected group from _selectedGroups
so it will crash at 
`void    Graph::clearSelection()
{
    // Note: getItem()->setSelected() actually _modify_ content
    // of _selectedNodes and _selectedGroups, a deep copy of theses
    // container is necessary to avoid iterating on a vector that
    // has changed while iterator has been modified.
    SelectedNodes selectedNodesCopy;
    std::copy( _selectedNodes.cbegin(),
                _selectedNodes.cend(),
                std::back_inserter(selectedNodesCopy) );
    for ( auto node : selectedNodesCopy )
        if ( node != nullptr &&
             node->getItem() != nullptr )
            node->getItem()->setSelected(false);
    _selectedNodes.clear();

    SelectedGroups selectedGroupsCopy;
    std::copy( _selectedGroups.cbegin(),
                _selectedGroups.cend(),
                std::back_inserter(selectedGroupsCopy) );
    qDebug() << "_selectedGroups size is: " << _selectedGroups.size();

    for ( auto group : selectedGroupsCopy )
        if ( group != nullptr &&
             group->getItem() != nullptr )
        {
            qDebug() << "group != nullptr && group->getItem() != nullptr";
            group->getItem()->setSelected(false);
        }
    _selectedGroups.clear();
}`
my try fixed it like this:
![image](https://user-images.githubusercontent.com/4347241/56710042-df236d00-6756-11e9-9cac-f5e4db45b127.png)

**Comment by cneben** [comment]
Thanks for the almost perfect bug report !

You are right: I will push the modification to remove the group from selection after the group has been removed. BTW, it looks like you are using a quite old version of the library, the latest selection code is more robust, it is not crashing even if the selection is not updated manually.
