### ISSUE TITLE
The _ports of a qan::NodeItem are not deleted upon destruction causing a memory leak

### ISSUE THREAD

**Issue by NielsBillen** [cneben/QuickQanava#84]
In our application, we regularly call `graph.qmlClearGraph()` and redraw our graph. However, this caused our application to consume an excessive amount of memory.

Upon further inspection, we traced the issue back to the _ports in the qan::NodeItem. We call `graph.insertPort(qan::Node* node, ...)`. In this method, a `PortItems*` is allocated on the heap and added to the _ports of the item `node` parameter.

When the `NodeItem` is destroyed, the elements of the `ports` are not deleted, nor was a parent set on the `PortItem` causing the memory leak.

Our proposed fix :

    NodeItem::~NodeItem()
    {
        // Delete all dock items
        for ( auto& dockItem : _dockItems ) {
            if ( dockItem )
                dockItem->deleteLater();
        }

        // Delete all ports
        for (auto& port : _ports) {
            if ( port  && port->parent() == Q_NULLPTR) {
                    port->deleteLater();
                }
           }
        }
    }

**Comment by JeJoProjects** [comment]
`if ( port ) {
            if (port->parent() == Q_NULLPTR) {
                port->deleteLater();
            }
}`

to

`if ( port  && port->parent() == Q_NULLPTR) 
{
      port->deleteLater();
}`

in the second loop.

**Comment by cneben** [comment]
Thank you both, PR is merged, problem is fixed on master.
