### ISSUE TITLE
Connecting ports via drag&drop isn't possible 

### ISSUE THREAD

**Issue by friedemannm** [cneben/QuickQanava#89]
It isn't possible to connect the OUTs with the INs. Unfortunately In none of the provided examples. See attached video.
Setup:
- Build with fresh git clone
- qmake build
- Qt. 5.12.3 
- OS X 10.14

[quickquanava_bug.mov.zip](https://github.com/cneben/QuickQanava/files/3221124/quickquanava_bug.mov.zip)

**Comment by enjoysmath** [comment]
I think some of the connections are restricted programatically in some of the examples.  That was my interpretation after running the samples.  But I'm a QuickQanava newbie.

**Comment by AntSion** [comment]
I have the same issue, even when creating another simple project, connecting ports with a visual connector doesn't work (and I have connectorEnabled set to true in my graph). A fix would be appreciated.

**Comment by AntSion** [comment]
I did a quick and dirty fix for that issue that could resolve the problem. I added this : 
`if (sourcePort)
 {
      connectorItem.state = "HILIGHT"
 }`
into VisualConnector.qml at the line 165. The problem was that when you try to bind twoports, the sourcenode tested in the if return null. I used sourcePort instead to bypass this.

**Comment by cneben** [comment]
Thank you @AntSion you where right, fixed in devel branch (an sorry for the answer delay...)
