### ISSUE TITLE
Right and double clicking on a group does not send the group to front and gives error

### ISSUE THREAD

**Issue by NielsBillen** [cneben/QuickQanava#90]
Right or double clicking on a group prints the following error:
```
"Could not convert argument 0 at"
	 "onGroupDoubleClicked@qrc:/QuickQanava/GraphView.qml:220"
```

The issue stems from the fact that at GraphView.qml:219 and 220 'graph.sendToFront' is called with the wrong argument. It is called with the group as argument:
```
    onGroupRightClicked: graph.sendToFront(group)
    onGroupDoubleClicked: graph.sendToFront(group)
```
while it should be called with the item of the group as argument:

```
onGroupRightClicked: {
    if (group.item) 
        graph.sendToFront(group.item);
}
onGroupDoubleClicked: {
    if (group.item) 
        graph.sendToFront(group.item);
}
```

**Comment by cneben** [comment]
Thank you very much @NielsBillen for the patch that has just been merged (and sorry for the merge delay!)
