### ISSUE TITLE
Examples don't run when building with CMake

### ISSUE THREAD

**Issue by eliemichel** [cneben/QuickQanava#93]
When building on Windows with mscv15 (2017), running any example, I get something like:

    QQmlApplicationEngine failed to load component
    qrc:/dataflow.qml:35 "qrc:/QuickQanava": no such directory

How is the library's qrc supposed to be transmitted to the executable btw? I cannot even run the example, so I am really unable to use QuickQanava at all. :/

LIkely related to #55 and #92 .

**Comment by cneben** [comment]
@eliemichel Sorry for the answer delay, merging @winterheart patch into devel branch.
